### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by t3rodrig** [barbagroup/bibtex#1]
Hello everybody,

I just want to thank you for your reproducibility practices. Thanks to that I could set my `$BIBINPUTS` path. By the way, I found something interesting. The `$BIBINPUTS` variable is not a shell environmental variable but a latex one. You can check this if you type the following command:

`$ texconfig conf`

which will show you your latex configuration. From this, you can see the kpathsea (latex) environmental variables, for example `$TEXMFHOME`. This variables can be expanded with the `kpsexpand` command:

`$ kpsexpand '$BIBINPUTS'`

This is what I did:

```
$ TEXMFHOME=`kpsexpand '$TEXMFHOME'`
$ mkdir -p $TEXMFHOME
$ BIBINPUTS=$TEXMFHOME/bibtex/bib
$ mkdir -p $BIBINPUTS
$ cd $BIBINPUTS
$ git clone https://github.com/barbagroup/bibtex.git
```

I hope you find it useful

Cheer,

Tonalli

**Comment by gforsyth** [comment]
Thanks for posting @t3rodrig and we're glad we could help.
